### ISSUE TITLE
Podział obowiązków

### ISSUE THREAD

**Issue by sokoloowski** [bazaragh/bazaragh#1]
- Sprecyzowanie kamieni milowych (prototyp, złożona implementacja, testowanie)
- Podział obowiązków w projekcie
- Ustalenie dat kamieni milowych (2 kamienie milowe przed IE)

**Comment by sokoloowski** [comment]
@PaulinaGacek - frontend
@HulekJakub - backend i zaplecze merytoryczne
@kskorupka - baza danych i modele
@sokoloowski - CI/CD, obsługa serwera, backend

**Comment by paulinagacek** [comment]
@sokoloowski tego już nie można zamknąć?
