### ISSUE TITLE
Złe wyświetlanie w przypadku null argumentów

### ISSUE THREAD

**Issue by HulekJakub** [bazaragh/bazaragh#20]
Tak wygląda strona oferty, gdy ta nie ma ceny ani opisu. Według mnie powinno wyświetlać napis "Za darmo" w przypadku gdy price jest None lub 0. Jakiś placeholder też byłby dobry w przypadku braku opisu.
![image](https://user-images.githubusercontent.com/49005176/232343830-cf001d85-9713-4d07-86ff-3fc35c51d190.png)

**Comment by sokoloowski** [comment]
Tu wina leży po stronie frontu, powinno zadziałać to:

```jinja2
{{ "Za darmo" if price is None else price }}
```
