### ISSUE TITLE
Tabele na dodatkowe dane

### ISSUE THREAD

**Issue by sokoloowski** [bazaragh/bazaragh#26]
Potrzebne są dwie tabele - akademiki i wydziały. Obecnie korzystamy z list w [`app/forms/security.py`](https://github.com/sokoloowski/pzio/blob/master/app/forms/security.py#L6), ale dobrze byłoby mieć to w bazie i powiązać z użytkownikami - będziemy mogli ładnie wyświetlać informacje o użytkowniku.

**Comment by sokoloowski** [comment]
Dodatkowo utworzyć podstrony w panelu admina, umożliwiające edycję i usuwanie tych danych przez moderatorów

**Comment by kskorupka** [comment]
tabele zrobione
