### ISSUE TITLE
Przesyłanie opinii o aplikacji

### ISSUE THREAD

**Issue by sokoloowski** [bazaragh/bazaragh#52]
Coś na wzór formularza kontaktowego, umożliwić wysłanie opinii również użytkownikom niezalogowanym. Dane z formularza przesłać mailem.

**Comment by paulinagacek** [comment]
@sokoloowski ja bym udostępniała taką możliwość jedynie zalogowanym, wtedy każdy użytkownik może wyrazić jednorazowo opinię i jakieś randomy nie będą pisać

**Comment by paulinagacek** [comment]
Stworzyłam kartę w pliku user_opinion.jinja żeby tam był form z jednym polem txt na wyrażenie opinii, max ileśtam znaków. Rutowanie na tą podstronę działa z przycisku "oceń nas". Jak dorobisz backend do tego @HulekJakub to ja to ostyluję.

**Comment by sokoloowski** [comment]
@paulinagacek backend dorobiony
