### ISSUE TITLE
Czat - stylowanie

### ISSUE THREAD

**Issue by sokoloowski** [bazaragh/bazaragh#70]
- [ ] Lista wątków jest nieczytelna
  ![image](https://github.com/sokoloowski/pzio/assets/39133910/5c26bc53-a23b-40fc-a8b1-3836558ebfcc)
- [ ] Widoczne dwa paski przewijania

**Comment by paulinagacek** [comment]
Frontendowe zmiany:
- [x] strona logowania i rejestracji jest za krótka na dużych ekranach i za wąska
- [x] dodać max szerokość `<p>` w footerze bo na dużych ekranach jest za szeroka
- [x] poprawić widok ogłoszeń sprzedającego
